### PR TITLE
To monix 2.8.2 ans scalajs 1.0.1

### PR DESCRIPTION
**Pull request by mathieuleclaire**

### CODE REVIEW

**Comment by mathieuleclaire** [comment]
SCALAJS_VERSION is set to 0.6.28 in the Travis setup, so that is fails.

**Comment by fdietze** [comment]
I adjusted the travis file and it works. Thank you!

**Comment by mathieuleclaire** [comment]
Great, do you think it is publishable ?

**Comment by fdietze** [comment]
I never had any maven release. Just use the latest commit hash via jitpack, like already done in scala.rx:

https://github.com/lihaoyi/scala.rx/blob/master/build.sbt#L93

**Comment by mathieuleclaire** [comment]
OK; perfect. Could you do a PR on the scala.rx repository with this hash then ?

**Comment by fdietze** [comment]
@mathieuleclaire 
https://github.com/lihaoyi/scala.rx/pull/166

**Comment by mathieuleclaire** [comment]
You rock, thanks.

**Pull request merged**
